import { Inter } from 'next/font/google'
import { Metadata } from 'next'
import React from 'react'
// TODO: Import the Toaster component from Payload
import { Toaster } from 'sonner'

import './globals.css'

import { Footer, Header } from '@/components'
import { Providers } from '@/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <Toaster richColors position="top-center" />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
