import { CollectionConfig } from 'payload'

import { archived, slugField } from '@/payload/fields'
import { categoriesOptions, cz } from '@/payload/data'
import { cs, en } from '@/translations'
import { dispatchEvents, revalidatePath } from '@/payload/hooks'
import { SA, SA_A, SA_A_O_Self_createdBy } from '@/payload/access'
import { createdBy } from '@/payload/fields'

export const Organizations: CollectionConfig = {
  slug: 'organizations',
  labels: {
    singular: {
      en: 'Organization',
      cs: 'Profil organizace',
    },
    plural: {
      en: 'Organizations',
      cs: 'Profily organizací',
    },
  },
  admin: {
    group: {
      en: 'Profiles',
      cs: 'Profily',
    },
    useAsTitle: 'title',
    defaultColumns: ['title', 'location', 'archived'],
    components: {
      beforeListTable: ['src/payload/components/Archived/index.tsx#Archived'],
    },
    hidden: ({ user }) => user?.role === 'organization' || user?.role === 'candidate',
  },
  hooks: {
    afterChange: [
      dispatchEvents([
        {
          operation: 'create',
          event: 'new-organization',
        },
      ]),
      revalidatePath
    ]
  },
  access: {
    /*
      Only users with the 'super-admin' role can create organizations.
      However, organizations are usually created from the frontend, i.e. anonymously.
      This is happening in the 'createProfile' hook in the Users collection, which
      is triggered when a new user is created. Even though only 'super-admin' users can
      create organization, the Local API has overrideAccess set to true.
    */
    create: SA,
    read: () => true,
    update: SA_A_O_Self_createdBy,
    delete: SA,
  },
  fields: [
    archived,
    {
      name: 'title',
      label: {
        en: 'Title',
        cs: 'Název',
      },
      type: 'text',
      required: true,
      access: {
        update: SA_A,
      },
    },
    slugField,
    {
      name: 'featured',
      label: {
        en: 'Featured',
        cs: 'Zvýrazněno ⭐',
      },
      type: 'checkbox',
      defaultValue: false,
      admin: {
        components: {
          Cell: 'src/payload/cells/index.ts#FeaturedCell',
        },
      },
      access: {
        create: SA,
        update: SA_A,
      },
    },
    {
      type: 'tabs',
      tabs: [
        {
          label: {
            en: 'Organization Details',
            cs: 'Detaily organizace'
          },
          fields: [
            {
              type: 'row',
              fields: [
                {
                  name: 'email',
                  label: {
                    en: 'Email',
                    cs: 'Email',
                  },
                  type: 'text',
                  admin: {
                    width: '50%',
                  },
                  unique: true,
                  required: true,
                },
                {
                  name: 'phone',
                  label: {
                    en: 'Phone',
                    cs: 'Telefon',
                  },
                  type: 'text',
                  admin: {
                    width: '50%',
                  },
                },
              ],
            },
            {
              type: 'row',
              fields: [
                {
                  name: 'location',
                  label: {
                    en: 'Location',
                    cs: 'Lokalita',
                  },
                  type: 'select',
                  hasMany: true,
                  options: cz,
                  admin: {
                    width: '50%',
                  },
                },
                {
                  name: 'vatId',
                  label: {
                    en: 'VAT ID',
                    cs: 'IČO',
                  },
                  type: 'text',
                  admin: {
                    width: '50%',
                  },
                  required: true,
                },
              ],
            },
            {
              name: 'categories',
              label: {
                en: 'Categories',
                cs: 'Kategorie',
              },
              type: 'select',
              options: categoriesOptions.map(option => ({
                label: {
                  en: en.search.options[option as keyof typeof en.search.options],
                  cs: cs.search.options[option as keyof typeof cs.search.options],
                },
                value: option,
              })),
              hasMany: true,
            },
            {
              type: 'row',
              fields: [
                {
                  name: 'logo',
                  label: {
                    en: 'Logo',
                    cs: 'Logo',
                  },
                  type: 'upload',
                  relationTo: 'logos',
                  admin: {
                    description: 'Logo of the organization. The filename will be autogenerated.',
                    width: '50%',
                  },
                },
                {
                  name: 'imageCover',
                  label: {
                    en: 'Image Cover',
                    cs: 'Obrázek',
                  },
                  type: 'upload',
                  relationTo: 'image-covers',
                  admin: {
                    width: '50%',
                  },
                },
              ],
            },
            {
              name: 'description',
              label: {
                en: 'Description',
                cs: 'Popis',
              },
              type: 'textarea',
            },
            {
              name: 'richText',
              label: {
                en: 'Rich Text',
                cs: 'Celý popis',
              },
              type: 'richText',
            },
            {
              name: 'url',
              label: {
                en: 'URL',
                cs: 'Odkaz',
              },
              type: 'text',
            },
          ],
        },
        {
          label: {
            en: 'Published Jobs',
            cs: 'Publikované inzeráty',
          },
          fields: [
            {
              name: 'jobsPublished',
              label: {
                en: 'Published Jobs',
                cs: 'Publikované inzeráty',
              },
              type: 'relationship',
              relationTo: 'jobs',
              maxDepth: 0,
              hasMany: true,
              unique: false,
              access: {
                update: SA,
              }
            },
          ],
        },
        {
          label: {
            en: 'Unpublished Jobs',
            cs: 'Koncepty'
          },
          fields: [
            {
              name: 'jobsUnpublished',
              label: {
                en: 'Unpublished Jobs',
                cs: 'Koncepty',
              },
              type: 'relationship',
              relationTo: 'jobs',
              maxDepth: 0,
              hasMany: true,
              unique: false,
              access: {
                update: SA,
              }
            },
          ],
        },
        {
          label: {
            en: 'Membership Custom Options',
            cs: 'Vlastní možnosti členství',
          },
          fields: [
            {
              name: 'jobsAllowed',
              label: {
                en: 'Number of remaining jobs',
                cs: 'Počet zbývajících inzerátů',
              },
              type: 'number',
              defaultValue: 0,
              access: {
                update: SA_A
              },
              required: true,
            },
            {
              type: 'array',
              name: 'memberships',
              access: {
                update: SA_A,
              },
              fields: [
                {
                  name: 'membership',
                  label: {
                    en: 'Membership',
                    cs: 'Členství',
                  },
                  type: 'relationship',
                  relationTo: 'memberships',
                  access: {
                    update: SA_A
                  },
                  required: true,
                },
                {
                  name: 'price',
                  type: 'number',
                  access: {
                    update: SA_A
                  },
                  required: true,
                }
              ],
            },
          ]
        }
      ],
    },
    createdBy
  ],
}
